# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

os:
  editPreset: "nvim-remote"
  editInTerminal: false

git:
  paging:
    colorArg: always
    pager: "delta --dark --paging=never --hunk-header-style=omit --file-style=omit"
